trigger:
- main

pool: raghavdevagent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
    displayName: 'Install Node.js'

- script: |
    npm install
    npm build
    npm test
  displayName: 'Install dependencies and run tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/nodejs-app.zip'
    replaceExistingArchive: true
  displayName: 'Archive build artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/nodejs-app.zip'
    artifactName: 'nodejs-app'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
