version: "3"
services:
    raghav:
      #  container_name: crazy_edison
      #  image: raghav/car-market-place
        restart: always
        build: .
        ports:
          - "3001:3001"
        links:
          - mongo
    mongo:
          container_name: mongo
          image: mongo
          volumes:
            - ./data:/data/db
          ports:
            - '27018:27017'